### ISSUE TITLE
Sometimes it log for too much times

### ISSUE THREAD

**Issue by tonyyyye** [bduggan/p6-log-async#22]
I don't know where is the problem, but a 
`method init()`
in my code causes 8 times printing, in which i only call it once with no loop.

**Comment by bduggan** [comment]
Could you provide an example?  I made a class with a method named `init` but don't see that behaviour:
```
$ more log.p6
use Log::Async;
logger.send-to($*ERR);

class A {
    method init {
    debug 'test';
    }
}

A.new.init();

$ perl6 log.p6
2018-06-08T09:07:54.055195-04:00 (1) debug: test
$
```

**Comment by tonyyyye** [comment]
I cannot submit the code right now. Need a couple of weeks till i can upload it.
As far as i remembered, it used init() in a sub class.

**Comment by tonyyyye** [comment]
$ cat Child.pm6
#!/usr/bin/env perl6
use Log::Async;
use lib <./>;
use Parent;
logger.send-to($*ERR);

class Child is Parent {
    method init {
        debug 'test child';
    }
}


my $child = Child.new.init();

$ cat Parent.pm6
#!/usr/bin/env perl6
use Log::Async;
logger.send-to($*ERR);

class Parent {
    method init {
        debug 'test parent';
    }
}
$ ./Child.pm6
2018-08-22T15:01:30.768467+08:00 (1) debug: test child
2018-08-22T15:01:30.768467+08:00 (1) debug: test child
$


In fact the Child just want the log to be shown only once.

**Comment by bduggan** [comment]
Hi,

The reason the log messages appear twice is because `send-to` is used twice, once in the parent and once in the child.  Every call to `send-to` will add another tap; so this code sends the messages to `$*ERR` twice.  You can just remove one of the calls to `send-to` (or put `send-to` into another file that uses `Parent` or `Child`; this is basically log initialization and should only be called once)

thanks
Brian
